apiVersion: v1
kind: Service
metadata:
  labels:
    app-dotaki: api
    env: {{ .Values.env }}
    release: {{ .Release.Name }} 
  name: {{.Chart.Name}}-{{.Chart.Version}}-{{ .Release.Name }}
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app-dotaki: api
    env: {{ .Values.env }}
  type: {{ .Values.service.type }}
