apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-node-gekko.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8081
  selector:
    app: kafka-producer
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
